# Generated by Django 5.0.2 on 2024-03-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('taste', models.CharField(max_length=400)),
                ('turnover', models.FloatField()),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
