# Generated by Django 5.0.2 on 2024-03-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='main',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
