# Generated by Django 5.0.2 on 2024-03-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_beer_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='img',
            field=models.ImageField(blank=True, upload_to='myapp/static/img'),
        ),
    ]
